### ISSUE TITLE
Unable to compile NumericSubtree.cxx with an old version of g++

### ISSUE THREAD

**Issue by amontoison** [ralna/GALAHAD#201]
@jfowkes @nimgould 
It could be the origin an internal error with the `icpc` compiler.
I found it when I opened a PR to cross-compile GALAHAD [here](https://github.com/JuliaPackaging/Yggdrasil/pull/7787).
```shell
[21:13:55] FAILED: libgalahad_single.so.p/src_ssids_NumericSubtree.cxx.o
[21:13:55] /opt/bin/i686-linux-gnu-libgfortran3-cxx03/i686-linux-gnu-g++ -Ilibgalahad_single.so.p -I. -I.. -Iinclude -I../include -I../src/dum/include -Isrc/ampl -I../src/ampl -I/workspace/destdir/include -D_FILE_OFFSET_BITS=64 -std=c++11 -O3 -fopenmp -DSPRAL_HAVE_SCHED_GETCPU -DSPRAL_HAVE_HWLOC -fPIC -DGALAHAD_SINGLE -DSPRAL_SINGLE -MD -MQ libgalahad_single.so.p/src_ssids_NumericSubtree.cxx.o -MF libgalahad_single.so.p/src_ssids_NumericSubtree.cxx.o.d -o libgalahad_single.so.p/src_ssids_NumericSubtree.cxx.o -c ../src/ssids/NumericSubtree.cxx
[21:13:55] In file included from ../include/ssids_cpu_factor.hxx:23:0,
[21:13:55]                  from ../include/ssids_cpu_NumericSubtree.hxx:10,
[21:13:55]                  from ../src/ssids/NumericSubtree.cxx:6:
[21:13:55] ../include/ssids_cpu_Workspace.hxx: In member function ‘void spral::ssids::cpu::Workspace::alloc_and_align(size_t)’:
[21:13:55] ../include/ssids_cpu_Workspace.hxx:37:11: error: ‘align’ is not a member of ‘std’
[21:13:55]        if(!std::align(align, sz, mem_aligned_, sz_)) throw std::bad_alloc();
[21:13:55]            ^
[21:13:55] In file included from ../include/ssids_cpu_NumericSubtree.hxx:11:0,
[21:13:55]                  from ../src/ssids/NumericSubtree.cxx:6:
[21:13:55] ../include/ssids_cpu_BuddyAllocator.hxx: In constructor ‘spral::ssids::cpu::buddy_alloc_internal::Page<CharAllocator>::Page(size_t, const CharAllocator&)’:
[21:13:55] ../include/ssids_cpu_BuddyAllocator.hxx:75:7: error: ‘align’ is not a member of ‘std’
[21:13:55]        std::align(align, size, to_align, space);
[21:13:55]        ^
[21:13:55] In file included from ../src/ssids/NumericSubtree.cxx:6:0:
[21:13:55] ../include/ssids_cpu_NumericSubtree.hxx: In constructor ‘spral::ssids::cpu::NumericSubtree<posdef, T, PAGE_SIZE, FactorAlloc>::NumericSubtree(const spral::ssids::cpu::SymbolicSubtree&, const T*, const T*, void**, const spral::ssids::cpu::cpu_factor_options&, spral::ssids::cpu::ThreadStats&)’:
[21:13:55] ../include/ssids_cpu_NumericSubtree.hxx:115:16: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                 depend(in: parent_lcol[0:1])
[21:13:55]                 ^
[21:13:55] ../include/ssids_cpu_NumericSubtree.hxx:179:16: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                 depend(inout: this_lcol[0:1]) \
[21:13:55]                 ^
[21:13:55] In file included from ../src/ssids/NumericSubtree.cxx:13:0:
[21:13:55] ../include/ssids_cpu_AppendAlloc.hxx: In member function ‘void* spral::ssids::cpu::append_alloc_internal::Page::allocate(size_t)’:
[21:13:55] ../include/ssids_cpu_AppendAlloc.hxx:50:11: error: ‘align’ is not a member of ‘std’
[21:13:55]        if(!std::align(align, sz, ptr_, space_)) return nullptr;
[21:13:55]            ^
[21:13:55] [549/1106] Compiling C++ object libgalahad_single.so.p/src_ssids_SymbolicSubtree.cxx.o
[21:13:55] [550/1106] Compiling C++ object libgalahad_single.so.p/src_ssids_ldlt_app.cxx.o
[21:13:55] FAILED: libgalahad_single.so.p/src_ssids_ldlt_app.cxx.o
[21:13:55] /opt/bin/i686-linux-gnu-libgfortran3-cxx03/i686-linux-gnu-g++ -Ilibgalahad_single.so.p -I. -I.. -Iinclude -I../include -I../src/dum/include -Isrc/ampl -I../src/ampl -I/workspace/destdir/include -D_FILE_OFFSET_BITS=64 -std=c++11 -O3 -fopenmp -DSPRAL_HAVE_SCHED_GETCPU -DSPRAL_HAVE_HWLOC -fPIC -DGALAHAD_SINGLE -DSPRAL_SINGLE -MD -MQ libgalahad_single.so.p/src_ssids_ldlt_app.cxx.o -MF libgalahad_single.so.p/src_ssids_ldlt_app.cxx.o.d -o libgalahad_single.so.p/src_ssids_ldlt_app.cxx.o -c ../src/ssids/ldlt_app.cxx
[21:13:55] In file included from ../include/ssids_cpu_kernels_ldlt_app.hxx:10:0,
[21:13:55]                  from ../src/ssids/ldlt_app.cxx:6:
[21:13:55] ../include/ssids_cpu_Workspace.hxx: In member function ‘void spral::ssids::cpu::Workspace::alloc_and_align(size_t)’:
[21:13:55] ../include/ssids_cpu_Workspace.hxx:37:11: error: ‘align’ is not a member of ‘std’
[21:13:55]        if(!std::align(align, sz, mem_aligned_, sz_)) throw std::bad_alloc();
[21:13:55]            ^
[21:13:55] In file included from ../src/ssids/ldlt_app.cxx:27:0:
[21:13:55] ../include/ssids_cpu_BuddyAllocator.hxx: In constructor ‘spral::ssids::cpu::buddy_alloc_internal::Page<CharAllocator>::Page(size_t, const CharAllocator&)’:
[21:13:55] ../include/ssids_cpu_BuddyAllocator.hxx:75:7: error: ‘align’ is not a member of ‘std’
[21:13:55]        std::align(align, size, to_align, space);
[21:13:55]        ^
[21:13:55] ../src/ssids/ldlt_app.cxx: In static member function ‘static int spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::run_elim_pivoted(int, int, int*, T*, int, T*, spral::ssids::cpu::ldlt_app_internal_sgl::ColumnData<T, typename std::allocator_traits<Allocator>::rebind_alloc<int> >&, Backup&, const spral::ssids::cpu::cpu_factor_options&, int, T, T*, int, std::vector<spral::ssids::cpu::Workspace>&, const Allocator&, int)’:
[21:13:55] ../src/ssids/ldlt_app.cxx:1331:13: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]              depend(inout: a[blk*block_size*lda+blk*block_size:1]) \
[21:13:55]              ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1395:16: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                 depend(in: a[blk*block_size*lda+blk*block_size:1])     \
[21:13:55]                 ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1429:16: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                 depend(in: a[blk*block_size*lda+blk*block_size:1])     \
[21:13:55]                 ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1465:13: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]              depend(inout: perm[blk*block_size:1])
[21:13:55]              ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1492:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: a[jblk*block_size*lda+iblk*block_size:1]) \
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1529:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: a[jblk*block_size*lda+iblk*block_size:1]) \
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1569:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: upd_ij[0:1])                          \
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx: In static member function ‘static int spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::run_elim_unpivoted(int, int, int*, T*, int, T*, spral::ssids::cpu::ldlt_app_internal_sgl::ColumnData<T, typename std::allocator_traits<Allocator>::rebind_alloc<int> >&, Backup&, int*, const spral::ssids::cpu::cpu_factor_options&, int, T, T*, int, std::vector<spral::ssids::cpu::Workspace>&, const Allocator&)’:
[21:13:55] ../src/ssids/ldlt_app.cxx:1794:13: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]              depend(inout: a[blk*block_size*lda+blk*block_size:1])
[21:13:55]              ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1858:16: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                 depend(in: a[blk*block_size*lda+blk*block_size:1])         \
[21:13:55]                 ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1888:16: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                 depend(in: a[blk*block_size*lda+blk*block_size:1])         \
[21:13:55]                 ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1936:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: a[jblk*block_size*lda+iblk*block_size:1]) \
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx:1976:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: upd_ij[0:1])                          \
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx: In static member function ‘static void spral::ssids::cpu::ldlt_app_internal_sgl::LDLT<T, BLOCK_SIZE, Backup, use_tasks, debug, Allocator>::restore(int, int, int, int*, T*, int, T*, spral::ssids::cpu::ldlt_app_internal_sgl::ColumnData<T, typename std::allocator_traits<Allocator>::rebind_alloc<int> >&, Backup&, const int*, const int*, int, std::vector<spral::ssids::cpu::Workspace>&, T*, int)’:
[21:13:55] ../src/ssids/ldlt_app.cxx:2189:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: a[jblk*block_size*lda+iblk*block_size:1])
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx:2207:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: a[jblk*block_size*lda+iblk*block_size:1])
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx:2219:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: a[jblk*block_size*lda+iblk*block_size:1]) \
[21:13:55]                    ^
[21:13:55] ../src/ssids/ldlt_app.cxx:2247:19: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]                    depend(inout: upd_ij[0:1])
[21:13:55]                    ^
```

**Comment by amontoison** [comment]
@mjacobe We have exactly the same file in the GitHub repository of `SPRAL`.
Is it something that we should fix even if the compilation works with more recent compilers or just a bug with older compilers?

**Comment by amontoison** [comment]
@mjacobse

**Comment by mjacobse** [comment]
The support for compilers/standard libraries that do not have `std::align` defined was removed from SPRAL with https://github.com/ralna/spral/pull/100 and https://github.com/ralna/spral/pull/101. Since then, SPRAL requires this C++11 feature (https://en.cppreference.com/w/cpp/memory/align) to be implemented. If a compiler/standard library does not fully support C++11, that is not really a bug, but it means that it does not meet the requirements for compiling SPRAL.

For gcc, `std::align` seems to be implemented since version 5.1 (https://godbolt.org/z/7Gs8eqT9v), which was released almost 9 years ago.

**Comment by amontoison** [comment]
Thanks for your quick answer @mjacobse! 
I was more thinking about the errors with OpenMP:
```shell
[21:13:55] ../src/ssids/ldlt_app.cxx:1331:13: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]              depend(inout: a[blk*block_size*lda+blk*block_size:1]) \
```
```shell
[21:13:55] ../src/ssids/ldlt_app.cxx:1794:13: error: expected ‘#pragma omp’ clause before ‘depend’
[21:13:55]              depend(inout: a[blk*block_size*lda+blk*block_size:1])
```

**Comment by jfowkes** [comment]
@amontoison icpc has been deprecated and removed from all recent Intel C++ compiler releases in favour of icpx, I see no reason whatsoever to support a deprecated compiler.

With the switch that Intel are making to ifx and icpx they are dropping Mac support (ironic given that they use LLVM as the backend) but this is almost certainly political since modern macs no longer use Intel (or even x86) CPUs.

**Comment by jfowkes** [comment]
Similarly there is no good reason whatsoever to support ancient versions of GCC.

**Comment by nimgould** [comment]
Agreed, back support for defunct compilers is a waste of effort

**Comment by amontoison** [comment]
Nick and Jari, the issue was not to compile with `icpc` but just to understand if the error with the older g++ compiler is not a warning now.
It could lead to sequential execution.

I completely disagree about ancient versions of GCC.
Libraries linked with `libgfortran3`, `libgfortran4` and `libgfortran5`  are incompatible if we link them together (see [here](https://docs.binarybuilder.org/dev/tricksy_gotchas/).
For this reason we need a GCC <= 6 for `libgfortran3`.
I don't compile with old compilers for pleasure.

Note that it worked fine with GCC 5.2.0 `libgfortran3`. :smiley: 

To maximize compatibility, we always try to compile with older compilers in the cross-compiler.

**Comment by nimgould** [comment]
OK, Alexis, I take your point. As this is C++, I am afraid that we will need someone who understands the language for an informed view as how to proceed.

**Comment by amontoison** [comment]
Off-topic: I was able to compile GALAHAD on all platforms with the Meson build systems https://github.com/JuliaPackaging/Yggdrasil/pull/7787 :tada: :tada: :tada: 
It means that the Julia users don't need to compile GALAHAD for for using the Julia interface GALAHAD.jl.

**Comment by nimgould** [comment]
That is very good news.

When you get time, I would still like to know how I can set up my GALAHAD so that it links into Julia. I think the pieces are in place, it is just that I don't know how they join together. You did show me last time you visited, but I lost the instructions and need to make myself a proper note (indeed a README so that anyone else foolish to go this route can do so).

**Comment by mjacobse** [comment]
> Thanks for your quick answer @mjacobse! I was more thinking about the errors with OpenMP:

Oh I see, sorry. I think that issue is not really related to C++, but rather OpenMP, which I am not very familiar with. But it appears that the `depend` clause was only introduced with OpenMP 4.0 (https://docs.oracle.com/cd/E37069_01/html/E37081/gozsa.html). This version is supported since gcc 4.9 (https://gcc.gnu.org/wiki/openmp), so it will not work with gcc 4.8 for example (over 10 years old). See https://godbolt.org/z/hPsWej1bY vs. https://godbolt.org/z/EMx14188T

**Comment by nimgould** [comment]
I seem to recall at the time that OMP4 was a requirement for spral

**Comment by jfowkes** [comment]
Yes I believe OpenMP 4.0 is a requirement as that is what SPRAL was developed with.

**Comment by amontoison** [comment]
Ok, so everything is fine.
Thanks again @mjacobse for your help!
